// auth.ts
import NextAuth from "next-auth"
import GitHub from "next-auth/providers/github"
import { db } from "@/db"
import { users } from "@/db/schema"
import { eq } from "drizzle-orm"

export const { handlers, signIn, signOut, auth } = NextAuth({
  providers: [
    GitHub({
      clientId: process.env.GITHUB_ID,
      clientSecret: process.env.GITHUB_SECRET,
    }),
  ],
  secret: process.env.AUTH_SECRET,
  callbacks: {
    async signIn({ user }) {
      // 1. Check if email is valid
      if (!user.email) return false;

      // 2. Check if user exists in YOUR database
      const existingUser = await db.query.users.findFirst({
        where: eq(users.email, user.email),
      });

      // 3. If not, create them!
      if (!existingUser) {
        try {
          await db.insert(users).values({
            email: user.email,
            name: user.name || "Anonymous",
            image: user.image,
            // id is auto-generated by your schema
          });
        } catch (error) {
          console.error("Failed to create user in DB:", error);
          return false; // Fail the login if DB write fails
        }
      }

      return true; // Allow the login
    },
  },
})